version: '3.2'

services:
  base:
    build:
      context: .
    image: 'moz-datapipeline'
    env_file: .env
    entrypoint: /bin/bash
    volumes:
      - '.:/var/pipeline/work'

  pipeline:
    image: moz-datapipeline
    env_file: .env
    volumes:
      - type: bind
        source: ./output
        target: /var/pipeline/output
      - type: bind
        source: ./source
        target: /var/pipeline/source
        read_only: true
    command: bash ./main.sh

volumes:
  output:
  source:
