version: '3.2'

services:
  base:
    build:
      context: .
    image: 'moz-datapipeline'
    env_file: .env
    volumes:
      - '.:/home/geolambda/work'

  moz-datapipeline:
    container_name: moz-datapipeline
    env_file: .env
    volumes:
      - type: bind
        source: ./output
        target: /var/pipeline/output
      - type: bind
        source: ./source
        target: /var/pipeline/source
        read_only: true
    command: bash ./main.sh

volumes:
  output:
  source:
