version: '3.2'

services:
  moz-datapipeline:
    environment:
      # When running docker in docker the volume bindings in the inner docker
      # are always relative to the root because we're using the same socket.
      # Because of this whenever we need to access one of the root volumes
      # (like source) we need to use the full path. Since this is not naturally
      # available inside the container we need to pass a variable.
      - ROOT_DIR=${PWD}
      # Set via env:
      # - S3_BUCKET
      # - AWS_ACCESS_KEY_ID
      # - AWS_SECRET_ACCESS_KEY
    build: ./
    container_name: moz-datapipeline
    volumes:
      - type: bind
        source: ./output
        target: /var/pipeline/output
      - type: bind
        source: ./.tmp
        target: /var/pipeline/.tmp
      - type: bind
        source: ./source
        target: /var/pipeline/source
        read_only: true
      - /var/run/docker.sock:/var/run/docker.sock
